### ISSUE TITLE
Create config.yml

### ISSUE THREAD

**Issue by andrejsharapov** [andrejsharapov/nuxt-app#18]
.github/ISSUE_TEMPLATE/config.yml

[docs](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) | [examples](https://github.com/nuxt/nuxt.js/issues/new/choose)

```
blank_issues_enabled: false
contact_links:
  - name: All other issues
    url: https://
    about: |
      Message.
```
